version: '2.4'

services:
    mp_db: 
        build: sources/monopoly-db-scheme
        restart: on-failure
        user: 1000:1000
        networks:
            monopoly_network:
                ipv4_address: 172.28.0.1
                
    mp_api_gw:
        build: sources/monopoly-api-gateway
        restart: on-failure
        user: 1000:1000
        volumes:
            - ./configuration:/configuration
        networks:
            monopoly_network:
                ipv4_address: 172.28.0.2
                
    mp_users:
        build: sources/monopoly-users-service
        restart: on-failure
        user: 1000:1000
        volumes:
            - ./configuration:/app/configuration
        networks:
            monopoly_network:
                ipv4_address: 172.28.0.3
                
    mp_lobbies:
        build: sources/monopoly-lobbies-service
        restart: on-failure
        user: 1000:1000
        volumes_from:
            - mp_users
        networks:
            monopoly_network:
                ipv4_address: 172.28.0.4
                
networks:
    monopoly_network:
        name: monopoly_network
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.28.0.0/16"
